"""Capture lifecycle, archive, and cache constants."""

# Capture cache behavior
CACHE_SUBDIR_NAME = "cache"
CLEAR_CACHE_ON_EXIT = True
CACHE_CLEANUP_RETRY_INTERVAL_MS = 100
CACHE_CLEANUP_MAX_ATTEMPTS = 100

# Capture Lifecycle Timing
CAPTURE_THREAD_ARM_DELAY_SEC = 0.05
STOP_CAPTURE_ACK_TIMEOUT_SEC = 0.2
STOP_CAPTURE_ACK_RETRIES = 1
STOP_CAPTURE_DRAIN_SEC = 0.15
STOP_CAPTURE_FINAL_DRAIN_SEC = 0.02
CLEAR_CAPTURE_DRAIN_SEC = 0.05

# Archive Writer Timing
ARCHIVE_WRITER_QUEUE_TIMEOUT_SEC = 0.1
ARCHIVE_WRITER_FLUSH_SWEEP_INTERVAL = 1000
ARCHIVE_WRITER_GIL_YIELD_SEC = 0.002
ARCHIVE_WRITER_JOIN_TIMEOUT_SEC = 15.0
