"""Default ADC filtering configuration values."""

FILTER_DEFAULT_ENABLED = False
FILTER_DEFAULT_MAIN_TYPE = "none"
FILTER_DEFAULT_ORDER = 2
FILTER_DEFAULT_LOW_CUTOFF_HZ = 5.0
FILTER_DEFAULT_HIGH_CUTOFF_HZ = 200.0

FILTER_NOTCH1_DEFAULT_ENABLED = True
FILTER_NOTCH1_DEFAULT_FREQ_HZ = 60.0
FILTER_NOTCH1_DEFAULT_Q = 30.0

FILTER_NOTCH2_DEFAULT_ENABLED = True
FILTER_NOTCH2_DEFAULT_FREQ_HZ = 120.0
FILTER_NOTCH2_DEFAULT_Q = 30.0

FILTER_NOTCH3_DEFAULT_ENABLED = False
FILTER_NOTCH3_DEFAULT_FREQ_HZ = 180.0
FILTER_NOTCH3_DEFAULT_Q = 30.0