"""Pressure Map constants.

Canonical constants for Pressure Map processing and visualization.
Legacy SIGNAL_INTEGRATION_* names are retained for compatibility during refactor.
"""

from constants.plotting import MAX_PLOT_SWEEPS

# Channel/layout constants
SIGNAL_INTEGRATION_CHANNEL_COUNT = 5
SIGNAL_INTEGRATION_POSITION_ORDER = ["T", "B", "C", "L", "R"]
SIGNAL_INTEGRATION_GROUND_CHANNEL_INDEX = 0
SIGNAL_INTEGRATION_PZT1_MUX_COUNT = 2

# Filtering and integration defaults
DEFAULT_HPF_CUTOFF_HZ = 10.0
SIGNAL_INTEGRATION_HPF_FILTER_ORDER = 1
SIGNAL_INTEGRATION_DISABLED_HPF_CUTOFF_HZ = 0.0
SIGNAL_INTEGRATION_FALLBACK_MEAN_WINDOW_MULTIPLIER = 10
SIGNAL_INTEGRATION_NYQUIST_DIVISOR = 2.0

DEFAULT_INTEGRATION_WINDOW_SAMPLES = 30
DEFAULT_INTEGRATION_SCALE_BY_DT = False
SIGNAL_INTEGRATION_WINDOW_MIN_SAMPLES = 1
SIGNAL_INTEGRATION_WINDOW_MAX_SAMPLES = 100000

# Display buffer and window defaults
DEFAULT_DISPLAY_WINDOW_SEC = 1.0
SIGNAL_INTEGRATION_DISPLAY_WINDOW_MIN_SEC = 0.1
SIGNAL_INTEGRATION_DISPLAY_WINDOW_MAX_SEC = 60.0
SIGNAL_INTEGRATION_DISPLAY_WINDOW_STEP_SEC = 0.5
SIGNAL_INTEGRATION_DISPLAY_WINDOW_DECIMALS = 1
SIGNAL_INTEGRATION_DISPLAY_SAMPLE_RATE_FALLBACK_HZ = 1000.0
SIGNAL_INTEGRATION_DISPLAY_BUFFER_MARGIN_SAMPLES = 1

# HPF control widget ranges
SIGNAL_INTEGRATION_HPF_CUTOFF_MIN_HZ = 0.0
SIGNAL_INTEGRATION_HPF_CUTOFF_MAX_HZ = 1000000.0
SIGNAL_INTEGRATION_HPF_CUTOFF_STEP_HZ = 1.0
SIGNAL_INTEGRATION_HPF_CUTOFF_DECIMALS = 2

# Plot rendering and throttling
SIGNAL_INTEGRATION_PLOT_LINE_WIDTH = 2
SIGNAL_INTEGRATION_REPEAT_LINE_WIDTH = 1.5
SIGNAL_INTEGRATION_AVERAGE_LINE_WIDTH = 3
SIGNAL_INTEGRATION_DIMMED_COLOR_FRACTION = 0.7
SIGNAL_INTEGRATION_FULL_SCALE_PADDING_FRACTION = 0.02
SIGNAL_INTEGRATION_CHANNEL_GRID_SPACING = 5
SIGNAL_INTEGRATION_LEGEND_OFFSET = (10, 10)
SIGNAL_INTEGRATION_PLOT_STRETCH = 1
SIGNAL_INTEGRATION_PLOT_MIN_HEIGHT_PX = 160
SIGNAL_INTEGRATION_PLOT_MAX_HEIGHT_PX = 240
SIGNAL_INTEGRATION_PLOT_UPDATE_FPS = 15.0
SIGNAL_INTEGRATION_PLOT_UPDATE_INTERVAL_SEC = 1.0 / SIGNAL_INTEGRATION_PLOT_UPDATE_FPS
SIGNAL_INTEGRATION_MAX_TOTAL_POINTS_TO_DISPLAY = 12000
SIGNAL_INTEGRATION_MIN_POINTS_PER_VISIBLE_CHANNEL = 500
SIGNAL_INTEGRATION_HISTORY_MIN_SWEEPS = 256
SIGNAL_INTEGRATION_HISTORY_DISPLAY_WINDOW_MULTIPLIER = 1
SIGNAL_INTEGRATION_HISTORY_INTEGRATION_WINDOW_MULTIPLIER = 1
SIGNAL_INTEGRATION_PROCESSING_WINDOW_MULTIPLIER = 2
SIGNAL_INTEGRATION_MAX_PROCESSING_SWEEPS = (
    MAX_PLOT_SWEEPS * SIGNAL_INTEGRATION_PROCESSING_WINDOW_MULTIPLIER
)
SIGNAL_INTEGRATION_Y_RANGE_PADDING_FRACTION = 0.1
SIGNAL_INTEGRATION_Y_RANGE_MIN_SPAN = 1e-9
SIGNAL_INTEGRATION_Y_RANGE_CENTER_DIVISOR = 2.0

# Canonical pressure-map aliases
PRESSURE_MAP_CHANNEL_COUNT = SIGNAL_INTEGRATION_CHANNEL_COUNT
PRESSURE_MAP_POSITION_ORDER = SIGNAL_INTEGRATION_POSITION_ORDER
PRESSURE_MAP_PLOT_UPDATE_FPS = SIGNAL_INTEGRATION_PLOT_UPDATE_FPS
PRESSURE_MAP_PLOT_UPDATE_INTERVAL_SEC = SIGNAL_INTEGRATION_PLOT_UPDATE_INTERVAL_SEC

