"""Pressure Map constants.

Canonical constants for Pressure Map processing and visualization.
Legacy SIGNAL_INTEGRATION_* names are retained for compatibility during refactor.
"""

from constants.plotting import MAX_PLOT_SWEEPS
from constants.shear import DEFAULT_NORMAL_FORCE_SENSOR_SPACING_MM

# Channel/layout constants
SIGNAL_INTEGRATION_CHANNEL_COUNT = 5
SIGNAL_INTEGRATION_POSITION_ORDER = ["T", "B", "C", "L", "R"]
SIGNAL_INTEGRATION_GROUND_CHANNEL_INDEX = 0
SIGNAL_INTEGRATION_PZT1_MUX_COUNT = 2

# Filtering and integration defaults
DEFAULT_HPF_CUTOFF_HZ = 10.0
SIGNAL_INTEGRATION_HPF_FILTER_ORDER = 1
SIGNAL_INTEGRATION_DISABLED_HPF_CUTOFF_HZ = 0.0
SIGNAL_INTEGRATION_FALLBACK_MEAN_WINDOW_MULTIPLIER = 10
SIGNAL_INTEGRATION_NYQUIST_DIVISOR = 2.0

DEFAULT_INTEGRATION_WINDOW_SAMPLES = 30
DEFAULT_INTEGRATION_SCALE_BY_DT = False
SIGNAL_INTEGRATION_WINDOW_MIN_SAMPLES = 1
SIGNAL_INTEGRATION_WINDOW_MAX_SAMPLES = 100000

# Display buffer and window defaults
DEFAULT_DISPLAY_WINDOW_SEC = 1.0
SIGNAL_INTEGRATION_DISPLAY_WINDOW_MIN_SEC = 0.1
SIGNAL_INTEGRATION_DISPLAY_WINDOW_MAX_SEC = 60.0
SIGNAL_INTEGRATION_DISPLAY_WINDOW_STEP_SEC = 0.5
SIGNAL_INTEGRATION_DISPLAY_WINDOW_DECIMALS = 1
SIGNAL_INTEGRATION_DISPLAY_SAMPLE_RATE_FALLBACK_HZ = 1000.0
SIGNAL_INTEGRATION_DISPLAY_BUFFER_MARGIN_SAMPLES = 1

# HPF control widget ranges
SIGNAL_INTEGRATION_HPF_CUTOFF_MIN_HZ = 0.0
SIGNAL_INTEGRATION_HPF_CUTOFF_MAX_HZ = 1000000.0
SIGNAL_INTEGRATION_HPF_CUTOFF_STEP_HZ = 1.0
SIGNAL_INTEGRATION_HPF_CUTOFF_DECIMALS = 2

# Plot rendering and throttling
SIGNAL_INTEGRATION_PLOT_LINE_WIDTH = 2
SIGNAL_INTEGRATION_REPEAT_LINE_WIDTH = 1.5
SIGNAL_INTEGRATION_AVERAGE_LINE_WIDTH = 3
SIGNAL_INTEGRATION_DIMMED_COLOR_FRACTION = 0.7
SIGNAL_INTEGRATION_FULL_SCALE_PADDING_FRACTION = 0.02
SIGNAL_INTEGRATION_CHANNEL_GRID_SPACING = 5
SIGNAL_INTEGRATION_LEGEND_OFFSET = (10, 10)
SIGNAL_INTEGRATION_PLOT_STRETCH = 1
SIGNAL_INTEGRATION_PLOT_MIN_HEIGHT_PX = 160
SIGNAL_INTEGRATION_PLOT_MAX_HEIGHT_PX = 240
SIGNAL_INTEGRATION_PLOT_UPDATE_FPS = 30.0
SIGNAL_INTEGRATION_PLOT_UPDATE_INTERVAL_SEC = 1.0 / SIGNAL_INTEGRATION_PLOT_UPDATE_FPS
SIGNAL_INTEGRATION_MAX_TOTAL_POINTS_TO_DISPLAY = 12000
SIGNAL_INTEGRATION_MIN_POINTS_PER_VISIBLE_CHANNEL = 500
SIGNAL_INTEGRATION_HISTORY_MIN_SWEEPS = 256
SIGNAL_INTEGRATION_HISTORY_DISPLAY_WINDOW_MULTIPLIER = 1
SIGNAL_INTEGRATION_HISTORY_INTEGRATION_WINDOW_MULTIPLIER = 1
SIGNAL_INTEGRATION_PROCESSING_WINDOW_MULTIPLIER = 2
SIGNAL_INTEGRATION_MAX_PROCESSING_SWEEPS = (
    MAX_PLOT_SWEEPS * SIGNAL_INTEGRATION_PROCESSING_WINDOW_MULTIPLIER
)
SIGNAL_INTEGRATION_Y_RANGE_PADDING_FRACTION = 0.1
SIGNAL_INTEGRATION_Y_RANGE_MIN_SPAN = 1e-9
SIGNAL_INTEGRATION_Y_RANGE_CENTER_DIVISOR = 2.0

# Canonical pressure-map aliases
PRESSURE_MAP_CHANNEL_COUNT = SIGNAL_INTEGRATION_CHANNEL_COUNT
PRESSURE_MAP_POSITION_ORDER = SIGNAL_INTEGRATION_POSITION_ORDER
PRESSURE_MAP_PLOT_UPDATE_FPS = SIGNAL_INTEGRATION_PLOT_UPDATE_FPS
PRESSURE_MAP_PLOT_UPDATE_INTERVAL_SEC = SIGNAL_INTEGRATION_PLOT_UPDATE_INTERVAL_SEC

# Pressure-map backend.
PRESSURE_QUADRANT_TOP_RIGHT = "TR"
PRESSURE_QUADRANT_TOP_LEFT = "TL"
PRESSURE_QUADRANT_BOTTOM_LEFT = "BL"
PRESSURE_QUADRANT_BOTTOM_RIGHT = "BR"
PRESSURE_ACTIVE_QUADRANTS = (
    PRESSURE_QUADRANT_TOP_RIGHT,
    PRESSURE_QUADRANT_TOP_LEFT,
    PRESSURE_QUADRANT_BOTTOM_LEFT,
    PRESSURE_QUADRANT_BOTTOM_RIGHT,
)
PRESSURE_AXIS_POSITIVE_DIRECTION = 1.0
PRESSURE_AXIS_NEGATIVE_DIRECTION = -1.0
DEFAULT_PRESSURE_GRID_MARGIN = 2
DEFAULT_PRESSURE_GRID_RESOLUTION = 21
DEFAULT_PRESSURE_SENSOR_SPACING_MM = DEFAULT_NORMAL_FORCE_SENSOR_SPACING_MM
DEFAULT_PRESSURE_DECAY_RATE = 0.8
DEFAULT_PRESSURE_DECAY_REF_DISTANCE_MM = 1.5
PRESSURE_GRID_MIN_RESOLUTION = 2
PRESSURE_GRID_MIN_MARGIN = 0
PRESSURE_GRID_MARGIN_SIDE_COUNT = 2
PRESSURE_OUTSIDE_MASK_VALUE = 0.0

# Pressure-map control defaults.
PRESSURE_SENSOR_SPACING_MIN_MM = 0.01
PRESSURE_SENSOR_SPACING_MAX_MM = 1000.0
PRESSURE_SENSOR_SPACING_STEP_MM = 0.05
PRESSURE_SENSOR_SPACING_DECIMALS = 3
PRESSURE_CIRCLE_DIAMETER_MIN_MM = 0.1
PRESSURE_CIRCLE_DIAMETER_MAX_MM = 1000.0
PRESSURE_CIRCLE_DIAMETER_STEP_MM = 0.1
PRESSURE_CIRCLE_DIAMETER_DECIMALS = 3
PRESSURE_GRID_RESOLUTION_MIN = 3
PRESSURE_GRID_RESOLUTION_MAX = 201
PRESSURE_GRID_RESOLUTION_STEP = 2
PRESSURE_GRID_MARGIN_MAX = 100
PRESSURE_GRID_MARGIN_STEP = 1
PRESSURE_DECAY_RATE_MIN = 0.0
PRESSURE_DECAY_RATE_MAX = 1000.0
PRESSURE_DECAY_RATE_STEP = 0.05
PRESSURE_DECAY_RATE_DECIMALS = 3
PRESSURE_DECAY_REF_DISTANCE_MIN_MM = 0.01
PRESSURE_DECAY_REF_DISTANCE_MAX_MM = 1000.0
PRESSURE_DECAY_REF_DISTANCE_STEP_MM = 0.05
PRESSURE_DECAY_REF_DISTANCE_DECIMALS = 3

# Pressure-map rendering and layout.
PRESSURE_MAP_COLORMAP_POINTS = 256
PRESSURE_MAP_COLORMAP_MIN_COLOR = "#000000"
PRESSURE_MAP_COLORMAP_MAX_COLOR = "#FFFFFF"
PRESSURE_MAP_ZERO_LEVEL_MIN = 0.0
PRESSURE_MAP_ZERO_LEVEL_MAX = 1.0
PRESSURE_MAP_LEVEL_EPSILON = 1e-12
PRESSURE_MAP_LEVEL_SCALE_SINGLE_SENSOR = 1.0
PRESSURE_MAP_LEVEL_SCALE_ALL_SENSORS = 2.0
DEFAULT_PRESSURE_MAP_MAX_INTENSITY = 0.15
PRESSURE_MAP_MAX_INTENSITY_MIN = 0.0
PRESSURE_MAP_MAX_INTENSITY_MAX = 1_000_000.0
PRESSURE_MAP_MAX_INTENSITY_STEP = 0.1
PRESSURE_MAP_MAX_INTENSITY_DECIMALS = 4
PRESSURE_MAP_WIDGET_MIN_HEIGHT_PX = 720
PRESSURE_MAP_PLOT_MIN_HEIGHT_PX = 650
PRESSURE_MAP_SENSOR_MARKER_SIZE_PX = 9
PRESSURE_MAP_SENSOR_MARKER_PEN_WIDTH_PX = 1.0
PRESSURE_MAP_SENSOR_MARKER_SYMBOL = "s"
PRESSURE_MAP_BACKGROUND_COLOR = "#000000"
PRESSURE_MAP_OVERLAY_COLOR = "#007BFF"
PRESSURE_MAP_PACKAGE_COLORS = (
    "#007BFF",
    "#00C853",
    "#FF4081",
    "#FFB300",
    "#00B8D4",
    "#D500F9",
    "#FF6D00",
    "#64DD17",
    "#536DFE",
)
PRESSURE_MAP_PACKAGE_SPACING_FRACTION = 1.0
PRESSURE_MAP_PACKAGE_VIEW_PADDING_FRACTION = 0.04
PRESSURE_MAP_SENSOR_MARKER_PEN_COLOR = PRESSURE_MAP_OVERLAY_COLOR
PRESSURE_MAP_SENSOR_MARKER_BRUSH_COLOR = PRESSURE_MAP_OVERLAY_COLOR
PRESSURE_MAP_CIRCLE_Z = 5
PRESSURE_MAP_IMAGE_Z = 1
PRESSURE_MAP_SENSOR_Z = 10
PRESSURE_MAP_STRETCH = 4

# Pressure-point marker controls.
DEFAULT_PRESSURE_SHOW_MARKER = True
PRESSURE_MAP_PEAK_MARKER_SYMBOL = "x"
PRESSURE_MAP_PEAK_MARKER_COLOR = "#FF0000"
PRESSURE_MAP_PEAK_MARKER_SIZE_PX = 12
PRESSURE_MAP_PEAK_MARKER_PEN_WIDTH_PX = 1.5
PRESSURE_MAP_PEAK_MARKER_Z = PRESSURE_MAP_SENSOR_Z + 1

# Pressure-map display controls.
DEFAULT_PRESSURE_MIRROR = False

