"""Pressure Map tab constants.

Canonical constants module for Pressure Map tab rendering/update behavior.
Values are currently sourced from legacy signal-integration constants for
backward compatibility during refactor.
"""

from constants.signal_integration import (
    DEFAULT_DISPLAY_WINDOW_SEC,
    DEFAULT_HPF_CUTOFF_HZ,
    DEFAULT_INTEGRATION_WINDOW_SAMPLES,
    SIGNAL_INTEGRATION_AVERAGE_LINE_WIDTH,
    SIGNAL_INTEGRATION_DIMMED_COLOR_FRACTION,
    SIGNAL_INTEGRATION_DISABLED_HPF_CUTOFF_HZ,
    SIGNAL_INTEGRATION_DISPLAY_WINDOW_DECIMALS,
    SIGNAL_INTEGRATION_DISPLAY_WINDOW_MAX_SEC,
    SIGNAL_INTEGRATION_DISPLAY_WINDOW_MIN_SEC,
    SIGNAL_INTEGRATION_DISPLAY_WINDOW_STEP_SEC,
    SIGNAL_INTEGRATION_HISTORY_DISPLAY_WINDOW_MULTIPLIER,
    SIGNAL_INTEGRATION_HISTORY_INTEGRATION_WINDOW_MULTIPLIER,
    SIGNAL_INTEGRATION_HISTORY_MIN_SWEEPS,
    SIGNAL_INTEGRATION_HPF_CUTOFF_DECIMALS,
    SIGNAL_INTEGRATION_HPF_CUTOFF_MAX_HZ,
    SIGNAL_INTEGRATION_HPF_CUTOFF_MIN_HZ,
    SIGNAL_INTEGRATION_HPF_CUTOFF_STEP_HZ,
    SIGNAL_INTEGRATION_HPF_FILTER_ORDER,
    SIGNAL_INTEGRATION_LEGEND_OFFSET,
    SIGNAL_INTEGRATION_MAX_PROCESSING_SWEEPS,
    SIGNAL_INTEGRATION_MAX_TOTAL_POINTS_TO_DISPLAY,
    SIGNAL_INTEGRATION_MIN_POINTS_PER_VISIBLE_CHANNEL,
    SIGNAL_INTEGRATION_NYQUIST_DIVISOR,
    SIGNAL_INTEGRATION_PLOT_MAX_HEIGHT_PX,
    SIGNAL_INTEGRATION_PLOT_MIN_HEIGHT_PX,
    SIGNAL_INTEGRATION_PLOT_LINE_WIDTH,
    SIGNAL_INTEGRATION_PLOT_UPDATE_FPS,
    SIGNAL_INTEGRATION_PLOT_UPDATE_INTERVAL_SEC,
    SIGNAL_INTEGRATION_POSITION_ORDER,
    SIGNAL_INTEGRATION_REPEAT_LINE_WIDTH,
    SIGNAL_INTEGRATION_WINDOW_MAX_SAMPLES,
    SIGNAL_INTEGRATION_WINDOW_MIN_SAMPLES,
)

# Canonical Pressure Map update throttle aliases.
PRESSURE_MAP_PLOT_UPDATE_FPS = SIGNAL_INTEGRATION_PLOT_UPDATE_FPS
PRESSURE_MAP_PLOT_UPDATE_INTERVAL_SEC = SIGNAL_INTEGRATION_PLOT_UPDATE_INTERVAL_SEC
