"""Defaults for PZT MUX ghost-removal."""

PZT_GHOST_DEFAULT_ENABLED = False
PZT_GHOST_DEFAULT_ATTENUATION = 0.1
PZT_GHOST_ATTENUATION_MIN = 0.0
PZT_GHOST_ATTENUATION_MAX = 1.0
PZT_GHOST_ATTENUATION_DECIMALS = 3
PZT_GHOST_ATTENUATION_STEP = 0.05
PZT_GHOST_NOISE_MAD_SCALE = 1.4826
