"""Sensor configuration defaults and schema constants."""

SENSOR_LOCATION_CODES = ["T", "R", "C", "L", "B"]
DEFAULT_SENSOR_CONFIGURATION_NAME = "ARRAY_v1"
SENSOR_CONFIG_REVERSE_POLARITY_KEY = "reverse_polarity"
DEFAULT_SENSOR_REVERSE_POLARITY = False
SENSOR_POLARITY_NORMAL_MULTIPLIER = 1.0
SENSOR_POLARITY_REVERSED_MULTIPLIER = -1.0
SENSOR_REVERSE_POLARITY_LABEL = "Reverse Polarity"
DEFAULT_SENSOR_CONFIGURATION = {
    "name": DEFAULT_SENSOR_CONFIGURATION_NAME,
    "channel_sensor_map": ["T", "L", "B", "R", "C"],
    SENSOR_CONFIG_REVERSE_POLARITY_KEY: DEFAULT_SENSOR_REVERSE_POLARITY,
}

SENSOR_CONFIG_FILE_VERSION = 1
SENSOR_CONFIG_JSON_INDENT = 2
SENSOR_CONFIG_CHANNEL_COUNT = 5
SENSOR_CONFIG_ARRAY_ROWS = 3
SENSOR_CONFIG_ARRAY_COLS = 3
SENSOR_CONFIG_ARRAY_CELL_CHANNELS_MAX = 5
SENSOR_CONFIG_MUX_MIN = 1
SENSOR_CONFIG_MUX_MAX = 2
SENSOR_CONFIG_CHANNEL_MIN = 0
SENSOR_CONFIG_CHANNEL_MAX = 15
