"""Serial/protocol/configuration timing constants."""

# Serial Communication Settings
BAUD_RATE = 460800
SERIAL_TIMEOUT = 1.0
COMMAND_TERMINATOR = "***"

# Configuration Command Settings
CONFIG_RETRY_ATTEMPTS = 3
CONFIG_COMMAND_TIMEOUT = 1.0
CONFIG_RETRY_DELAY = 0.05
INTER_COMMAND_DELAY = 0.05

# Arduino Communication Timing
ARDUINO_RESET_DELAY = 2.0

# Buffer Optimization Settings
TARGET_LATENCY_SEC = 0.25
MAX_SAMPLES_BUFFER = 32000
USB_PACKET_SIZE = 64
DEFAULT_BUFFER_SIZE = 1
ARRAY_PZT_MAX_MUX_PAIRS_PER_BLOCK = 8000

# UI Control Ranges and Defaults (serial-adjacent controls)
BUFFER_SIZE_MIN = 1
BUFFER_SIZE_MAX = 10000
GROUND_PIN_MIN = 0
GROUND_PIN_MAX = 18
GROUND_PIN_DEFAULT = 0
REPEAT_COUNT_MIN = 1
REPEAT_COUNT_MAX = 16
REPEAT_COUNT_DEFAULT = 1
TIMED_RUN_MIN = 10
TIMED_RUN_MAX = 3600000
TIMED_RUN_DEFAULT = 1000
TIMED_CAPTURE_FINISH_SLACK_MS = 500

# Serial Reader / Protocol Constants
SERIAL_READER_IDLE_MS = 2
FORCE_READER_IDLE_MS = 10
SERIAL_READER_DEBUG_LOG_LIMIT = 10
SERIAL_PACKET_HEADER_BYTES = 4
SERIAL_PACKET_AVG_SAMPLE_TIME_BYTES = 2
SERIAL_PACKET_BLOCK_TIMESTAMP_BYTES = 8
SERIAL_PACKET_SAMPLE_COUNT_MAX = MAX_SAMPLES_BUFFER
SERIAL_PACKET_AVG_SAMPLE_TIME_MIN_US = 1
SERIAL_PACKET_AVG_SAMPLE_TIME_MAX_US = 200_000
SERIAL_PACKET_SPAN_MIN_FACTOR = 0.25
SERIAL_PACKET_SPAN_MAX_FACTOR = 12.0
SERIAL_PACKET_SPAN_TOLERANCE_US = 2000

# MCU Detection Constants
MCU_DETECTION_TIMEOUT_SEC = 2.0
MCU_DETECTION_POLL_INTERVAL_SEC = 0.01
TEENSY_SAMPLE_RATE_MAX_HZ = 1000000
