"""Shear detection and visualization constants."""

SHEAR_POSITION_CENTER = "C"
SHEAR_POSITION_LEFT = "L"
SHEAR_POSITION_RIGHT = "R"
SHEAR_POSITION_TOP = "T"
SHEAR_POSITION_BOTTOM = "B"
SHEAR_SENSOR_POSITIONS = (
    SHEAR_POSITION_CENTER,
    SHEAR_POSITION_LEFT,
    SHEAR_POSITION_RIGHT,
    SHEAR_POSITION_TOP,
    SHEAR_POSITION_BOTTOM,
)
SHEAR_OUTER_SENSOR_POSITIONS = (
    SHEAR_POSITION_LEFT,
    SHEAR_POSITION_RIGHT,
    SHEAR_POSITION_TOP,
    SHEAR_POSITION_BOTTOM,
)

SHEAR_HORIZONTAL_LEFT_INDEX = 0
SHEAR_HORIZONTAL_RIGHT_INDEX = 1
SHEAR_VERTICAL_TOP_INDEX = 0
SHEAR_VERTICAL_BOTTOM_INDEX = 1
SHEAR_ZERO_VALUE = 0.0
SHEAR_DEFAULT_ANGLE_DEG = 0.0
SHEAR_FULL_CIRCLE_DEG = 360.0

# Normal-force computation.
SHEAR_FORCE_TYPE_COMPRESSION = "compression"
SHEAR_FORCE_TYPE_TENSION = "tension"
SHEAR_FORCE_TYPE_NONE = "none"
NORMAL_FORCE_SENSOR_COUNT = len(SHEAR_SENSOR_POSITIONS)
NORMAL_FORCE_DENOMINATOR_EPSILON = 1e-12
DEFAULT_NORMAL_FORCE_SENSOR_SPACING_MM = 1.75

# Pressure-map backend.
PRESSURE_QUADRANT_TOP_RIGHT = "TR"
PRESSURE_QUADRANT_TOP_LEFT = "TL"
PRESSURE_QUADRANT_BOTTOM_LEFT = "BL"
PRESSURE_QUADRANT_BOTTOM_RIGHT = "BR"
PRESSURE_ACTIVE_QUADRANTS = (
    PRESSURE_QUADRANT_TOP_RIGHT,
    PRESSURE_QUADRANT_TOP_LEFT,
    PRESSURE_QUADRANT_BOTTOM_LEFT,
    PRESSURE_QUADRANT_BOTTOM_RIGHT,
)
PRESSURE_AXIS_POSITIVE_DIRECTION = 1.0
PRESSURE_AXIS_NEGATIVE_DIRECTION = -1.0
DEFAULT_PRESSURE_GRID_MARGIN = 2
DEFAULT_PRESSURE_GRID_RESOLUTION = 21
DEFAULT_PRESSURE_SENSOR_SPACING_MM = DEFAULT_NORMAL_FORCE_SENSOR_SPACING_MM
PRESSURE_GRID_MIN_RESOLUTION = 2
PRESSURE_GRID_MIN_MARGIN = 0
PRESSURE_GRID_MARGIN_SIDE_COUNT = 2
PRESSURE_OUTSIDE_MASK_VALUE = 0.0

# Pressure-map control defaults.
PRESSURE_SENSOR_SPACING_MIN_MM = 0.01
PRESSURE_SENSOR_SPACING_MAX_MM = 1000.0
PRESSURE_SENSOR_SPACING_STEP_MM = 0.05
PRESSURE_SENSOR_SPACING_DECIMALS = 3
PRESSURE_CIRCLE_DIAMETER_MIN_MM = 0.1
PRESSURE_CIRCLE_DIAMETER_MAX_MM = 1000.0
PRESSURE_CIRCLE_DIAMETER_STEP_MM = 0.1
PRESSURE_CIRCLE_DIAMETER_DECIMALS = 3
PRESSURE_GRID_RESOLUTION_MIN = 3
PRESSURE_GRID_RESOLUTION_MAX = 201
PRESSURE_GRID_RESOLUTION_STEP = 2
PRESSURE_GRID_MARGIN_MAX = 100
PRESSURE_GRID_MARGIN_STEP = 1
PRESSURE_MAP_COLORMAP_POINTS = 256
PRESSURE_MAP_COLORMAP_MIN_COLOR = "#000000"
PRESSURE_MAP_COLORMAP_MAX_COLOR = "#FFFFFF"
PRESSURE_MAP_ZERO_LEVEL_MIN = 0.0
PRESSURE_MAP_ZERO_LEVEL_MAX = 1.0
PRESSURE_MAP_LEVEL_EPSILON = 1e-12
PRESSURE_MAP_LEVEL_SCALE_SINGLE_SENSOR = 1.0
PRESSURE_MAP_LEVEL_SCALE_ALL_SENSORS = 2.0
PRESSURE_MAP_WIDGET_MIN_HEIGHT_PX = 500
PRESSURE_MAP_PLOT_MIN_HEIGHT_PX = 430
PRESSURE_MAP_SENSOR_MARKER_SIZE_PX = 9
PRESSURE_MAP_SENSOR_MARKER_PEN_WIDTH_PX = 1.0
PRESSURE_MAP_SENSOR_MARKER_SYMBOL = "s"
PRESSURE_MAP_BACKGROUND_COLOR = "#000000"
PRESSURE_MAP_OVERLAY_COLOR = "#007BFF"
PRESSURE_MAP_SENSOR_MARKER_PEN_COLOR = PRESSURE_MAP_OVERLAY_COLOR
PRESSURE_MAP_SENSOR_MARKER_BRUSH_COLOR = PRESSURE_MAP_OVERLAY_COLOR
PRESSURE_MAP_CIRCLE_Z = 5
PRESSURE_MAP_IMAGE_Z = 1
PRESSURE_MAP_SENSOR_Z = 10
PRESSURE_MAP_STRETCH = 4

# Settings persistence.
SHEAR_SETTINGS_VERSION = 1
SHEAR_SETTINGS_PAYLOAD_KEY = "shear_settings"
SHEAR_SETTINGS_APP_DIRNAME = ".adc_streamer"
SHEAR_SETTINGS_SUBDIR = "shear"
SHEAR_SETTINGS_LAST_FILENAME = "last_used_signal_integration_shear_settings.json"
SHEAR_SETTINGS_DEFAULT_FILENAME = "signal_integration_shear_settings.json"
SHEAR_SETTINGS_FILE_FILTER = "JSON Files (*.json);;All Files (*)"

# Calibration and threshold controls.
DEFAULT_SHEAR_NOISE_THRESHOLD = 0.0
SHEAR_NOISE_THRESHOLD_MIN = 0.0
SHEAR_NOISE_THRESHOLD_MAX = 1_000_000.0
SHEAR_NOISE_THRESHOLD_STEP = 0.1
SHEAR_NOISE_THRESHOLD_DECIMALS = 4

DEFAULT_SHEAR_CALIBRATION_GAIN = 1.0
SHEAR_CALIBRATION_GAIN_MIN = -1_000_000.0
SHEAR_CALIBRATION_GAIN_MAX = 1_000_000.0
SHEAR_CALIBRATION_GAIN_STEP = 0.1
SHEAR_CALIBRATION_GAIN_DECIMALS = 4

# Sensor-layout geometry in plot coordinates (millimeters).
DEFAULT_CIRCLE_DIAMETER_MM = 5.5
DEFAULT_SENSOR_SPACING_MM = 3.5
SHEAR_LAYOUT_BOUNDARY_PADDING_FRACTION = 0.1
SHEAR_SENSOR_SQUARE_SIDE_MM = 0.22
SHEAR_SENSOR_LABEL_OFFSET_MM = 0.35
SHEAR_AXIS_EQUAL_ASPECT_LOCKED = True

# Static layout appearance.
SHEAR_LAYOUT_BACKGROUND = "w"
SHEAR_LAYOUT_CIRCLE_COLOR = "#555555"
SHEAR_LAYOUT_SENSOR_FILL_COLOR = "#B8B8B8"
SHEAR_LAYOUT_SENSOR_OUTLINE_COLOR = "#777777"
SHEAR_LAYOUT_LABEL_COLOR = "#222222"
SHEAR_LAYOUT_GRID_ALPHA = 0.2
SHEAR_LAYOUT_CIRCLE_LINE_WIDTH_PX = 0.8
SHEAR_LAYOUT_SENSOR_LINE_WIDTH_PX = 0.5
SHEAR_LAYOUT_MIN_VISIBLE_LINE_WIDTH_PX = 0.5
SHEAR_LAYOUT_PENS_ARE_COSMETIC = True
SHEAR_STATIC_LAYOUT_Z = 1
SHEAR_LABEL_Z = 2
SHEAR_ARROW_Z = 10
SHEAR_VISUALIZATION_STRETCH = 3
SHEAR_VISUALIZATION_MIN_HEIGHT_PX = 500
SHEAR_PLOT_MIN_HEIGHT_PX = 430
SHEAR_SETTINGS_GRID_COLUMNS = 5
SHEAR_SETTINGS_HORIZONTAL_SPACING_PX = 4
SHEAR_SETTINGS_VERTICAL_SPACING_PX = 4
SHEAR_GAIN_LABEL_MAX_WIDTH_PX = 44
SHEAR_GAIN_SPIN_WIDTH_PX = 74
SHEAR_CONTROL_SPIN_WIDTH_PX = 96

# Dynamic arrow controls.
DEFAULT_ARROW_GAIN = 1.0
DEFAULT_ARROW_MAX_LENGTH_PX = 1.0
DEFAULT_ARROW_MIN_THRESHOLD = 0.0
DEFAULT_ARROW_WIDTH_SCALES = True
DEFAULT_ARROW_BASE_WIDTH_PX = 1.0
DEFAULT_ARROW_COLOR = "#FF0000"
SHEAR_ARROW_WIDTH_SCALE_RANGE_PX = 2.0
SHEAR_ARROW_WIDTH_REFERENCE_MAGNITUDE = 2.0
SHEAR_ARROW_MAX_WIDTH_PX = 8.0
SHEAR_ARROW_PEN_IS_COSMETIC = True
SHEAR_ARROW_HEAD_LENGTH_FRACTION = 0.14
SHEAR_ARROW_HEAD_WIDTH_FRACTION = 0.045
SHEAR_ARROW_MIN_HEAD_LENGTH_MM = 0.12
SHEAR_ARROW_MIN_HEAD_WIDTH_MM = 0.06

SHEAR_ARROW_GAIN_MIN = 0.0
SHEAR_ARROW_GAIN_MAX = 1_000_000.0
SHEAR_ARROW_GAIN_STEP = 0.1
SHEAR_ARROW_GAIN_DECIMALS = 4

SHEAR_ARROW_MIN_THRESHOLD_MIN = 0.0
SHEAR_ARROW_MIN_THRESHOLD_MAX = 1_000_000.0
SHEAR_ARROW_MIN_THRESHOLD_STEP = 0.1
SHEAR_ARROW_MIN_THRESHOLD_DECIMALS = 4

SHEAR_ARROW_BASE_WIDTH_MIN_PX = 0.1
SHEAR_ARROW_BASE_WIDTH_MAX_PX = 6.0
SHEAR_ARROW_BASE_WIDTH_STEP_PX = 0.1
SHEAR_ARROW_BASE_WIDTH_DECIMALS = 1

SHEAR_ARROW_MAX_LENGTH_MIN = 0.0
SHEAR_ARROW_MAX_LENGTH_MAX = 10.0
SHEAR_ARROW_MAX_LENGTH_STEP = 0.1
SHEAR_ARROW_MAX_LENGTH_DECIMALS = 2

# Readout formatting.
SHEAR_READOUT_MAGNITUDE_DECIMALS = 2
SHEAR_READOUT_ANGLE_DECIMALS = 0
SHEAR_COMPONENT_DECIMALS = 2
