"""UI and window layout constants."""

# UI Update Timing
FORCE_PLOT_DEBOUNCE_MS = 100
CONFIG_CHECK_INTERVAL = 100
SPECTRUM_UPDATE_INTERVAL_MS = 100
PLOT_UPDATE_FREQUENCY = 10

# Window and Layout Settings
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
WINDOW_MIN_FIT_WIDTH = 900
WINDOW_MIN_FIT_HEIGHT = 700
WINDOW_SCREEN_MARGIN_PX = 16
CONTROL_PANEL_STRETCH = 1
VISUALIZATION_PANEL_STRETCH = 3
MAIN_PANEL_LAYOUT_SPACING = 10
STATUS_SEPARATOR_WIDTH = 70
DEFAULT_WINDOW_SIZE = 10000
MAX_PLOT_COLUMNS = 6

# Visualization tab names.
TIME_SERIES_TAB_NAME = "Time Series"
PRESSURE_MAP_TAB_NAME = "Pressure Map"
SPECTRUM_TAB_NAME = "Spectrum"
SENSOR_TAB_NAME = "Sensor"

# Sweep range spinners
SWEEP_RANGE_MIN = 0
SWEEP_RANGE_MAX = 999999
SWEEP_RANGE_DEFAULT_MAX = 1000

# Window size spinner range
WINDOW_SIZE_MIN = 10
WINDOW_SIZE_MAX = 10000

# UI element heights
NOTES_INPUT_HEIGHT = 60
STATUS_TEXT_HEIGHT = 150
CHANNEL_SCROLL_HEIGHT = 80

# Maximum number of log lines to keep in status text window
MAX_LOG_LINES = 1000
